### ISSUE TITLE
u2fval run Error (Symbol not found: _SSLv2_method)

### ISSUE THREAD

**Issue by lukasz-romanowski** [Yubico/u2fval#19]
I install u2fval via pip

```
$ pip list
cachetools (1.1.5)
cffi (1.4.2)
cryptography (1.1.2)
enum34 (1.1.2)
idna (2.0)
ipaddress (1.0.16)
M2Crypto (0.22.5)
MySQL-python (1.2.5)
pip (7.1.2)
pyasn1 (0.1.9)
pyasn1-modules (0.0.8)
pycparser (2.14)
pycrypto (2.6.1)
pyOpenSSL (0.15.1)
python-u2flib-server (3.2.0)
setuptools (18.2)
six (1.10.0)
SQLAlchemy (1.0.11)
u2fval (0.9.1)
WebOb (1.5.1)
wheel (0.24.0)
```

_u2fval db init_ and _u2fval client create_ work fine
but when i run u2fval i have **error**:

```
$ u2fval run
Traceback (most recent call last):
  File "/Users/myuser/workspace/u2fval/.env/bin/u2fval", line 11, in <module>
    sys.exit(main())
  File "/Users/myuser/workspace/u2fval/.env/lib/python2.7/site-packages/u2fval/cli.py", line 196, in main
    handle_args(settings, args)
  File "/Users/myuser/workspace/u2fval/.env/lib/python2.7/site-packages/u2fval/cli.py", line 184, in handle_args
    handle_run(settings, args)
  File "/Users/myuser/workspace/u2fval/.env/lib/python2.7/site-packages/u2fval/cli.py", line 147, in handle_run
    from u2fval.core.api import create_application
  File "/Users/myuser/workspace/u2fval/.env/lib/python2.7/site-packages/u2fval/core/api.py", line 29, in <module>
    from u2fval.core.controller import U2FController
  File "/Users/myuser/workspace/u2fval/.env/lib/python2.7/site-packages/u2fval/core/controller.py", line 31, in <module>
    from u2flib_server.u2f_v2 import (start_register, complete_register,
  File "/Users/myuser/workspace/u2fval/.env/lib/python2.7/site-packages/u2flib_server/u2f_v2.py", line 28, in <module>
    from M2Crypto import X509
  File "/Users/myuser/workspace/u2fval/.env/lib/python2.7/site-packages/M2Crypto/__init__.py", line 22, in <module>
    import _m2crypto
  File "/Users/myuser/workspace/u2fval/.env/lib/python2.7/site-packages/M2Crypto/_m2crypto.py", line 28, in <module>
    __m2crypto = swig_import_helper()
  File "/Users/myuser/workspace/u2fval/.env/lib/python2.7/site-packages/M2Crypto/_m2crypto.py", line 24, in swig_import_helper
    _mod = imp.load_module('__m2crypto', fp, pathname, description)
ImportError: dlopen(/Users/myuser/workspace/u2fval/.env/lib/python2.7/site-packages/M2Crypto/__m2crypto.so, 2): Symbol not found: _SSLv2_method
  Referenced from: /Users/myuser/workspace/u2fval/.env/lib/python2.7/site-packages/M2Crypto/__m2crypto.so
  Expected in: flat namespace
 in /Users/myuser/workspace/u2fval/.env/lib/python2.7/site-packages/M2Crypto/__m2crypto.so
```

**Comment by dainnilsson** [comment]
No longer applicable as M2Crypto has been replaced.
