### ISSUE TITLE
pip install raise an AttributeError

### ISSUE THREAD

**Issue by patatetom** [Yubico/u2fval#6]
hi,
the `pip install u2fval` raise an AttributeError when package wheel (0.24.0) is present : 
```
# virtualenv u2fval.with.wheel
New python executable in u2fval.with.wheel/bin/python2
Also creating executable in u2fval.with.wheel/bin/python
Installing setuptools, pip, wheel...done.

# source u2fval.with.wheel/bin/activate

(u2fval.with.wheel) # pip list
pip (7.1.2)
setuptools (18.2)
wheel (0.24.0)

(u2fval.with.wheel) # pip install u2fval
Collecting u2fval
  Using cached u2fval-0.9.0.tar.gz
Collecting python-u2flib-server>=3.1 (from u2fval)
  Using cached python-u2flib-server-3.2.0.tar.gz
Collecting SQLAlchemy (from u2fval)
  Using cached SQLAlchemy-1.0.8.tar.gz
Collecting WebOb (from u2fval)
  Using cached WebOb-1.4.1.tar.gz
Collecting cachetools (from u2fval)
  Using cached cachetools-1.1.1-py2.py3-none-any.whl
Collecting M2Crypto (from python-u2flib-server>=3.1->u2fval)
  Using cached M2Crypto-0.22.3.tar.gz
Collecting pyasn1>=0.1.7 (from python-u2flib-server>=3.1->u2fval)
  Using cached pyasn1-0.1.8.tar.gz
Collecting pyasn1-modules (from python-u2flib-server>=3.1->u2fval)
  Using cached pyasn1-modules-0.0.7.tar.gz
Building wheels for collected packages: u2fval, python-u2flib-server, SQLAlchemy, WebOb, M2Crypto, pyasn1, pyasn1-modules
  Running setup.py bdist_wheel for u2fval
  Stored in directory: /root/.cache/pip/wheels/3d/37/d1/b63bc85cbb002c36597b8a45d60f465660e8fdc5ecd4ca4634
  Running setup.py bdist_wheel for python-u2flib-server
  Stored in directory: /root/.cache/pip/wheels/3f/8e/42/ba51284586e0b325ad09ff7f2683574020045eb96303a1f13c
  Running setup.py bdist_wheel for SQLAlchemy
  Stored in directory: /root/.cache/pip/wheels/e2/72/57/1ad7bf206e4a6fd87aeeb31bc0c442206dd2c3fba995a50ddc
  Running setup.py bdist_wheel for WebOb
  Stored in directory: /root/.cache/pip/wheels/15/ac/26/8a43d4896175cafa36cca3f3499912b23f42c2eb72f0febced
  Running setup.py bdist_wheel for M2Crypto
  Stored in directory: /root/.cache/pip/wheels/2b/60/e3/96b694fb9fd5bef8faaaabe4ad9ff0cb77aba69478dafda7fc
  Running setup.py bdist_wheel for pyasn1
  Stored in directory: /root/.cache/pip/wheels/c4/c5/95/c73b6aecd3119583f44a299c290a2d94bc3f67ae38728af1ef
  Running setup.py bdist_wheel for pyasn1-modules
  Stored in directory: /root/.cache/pip/wheels/82/4f/72/c1306b22a5219e5e46eda7938804c6194748a5fe34198fa557
Successfully built u2fval python-u2flib-server SQLAlchemy WebOb M2Crypto pyasn1 pyasn1-modules
Installing collected packages: M2Crypto, pyasn1, pyasn1-modules, python-u2flib-server, SQLAlchemy, WebOb, cachetools, u2fval
Exception:
Traceback (most recent call last):
  File "/root/u2fval.with.wheel/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/root/u2fval.with.wheel/lib/python2.7/site-packages/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/root/u2fval.with.wheel/lib/python2.7/site-packages/pip/req/req_set.py", line 646, in install
    **kwargs
  File "/root/u2fval.with.wheel/lib/python2.7/site-packages/pip/req/req_install.py", line 803, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/root/u2fval.with.wheel/lib/python2.7/site-packages/pip/req/req_install.py", line 998, in move_wheel_files
    isolated=self.isolated,
  File "/root/u2fval.with.wheel/lib/python2.7/site-packages/pip/wheel.py", line 479, in move_wheel_files
    maker.make_multiple(['%s = %s' % kv for kv in console.items()])
  File "/root/u2fval.with.wheel/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 364, in make_multiple
    filenames.extend(self.make(specification, options))
  File "/root/u2fval.with.wheel/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 353, in make
    self._make_script(entry, filenames, options=options)
  File "/root/u2fval.with.wheel/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 244, in _make_script
    script = self._get_script_text(entry).encode('utf-8')
  File "/root/u2fval.with.wheel/lib/python2.7/site-packages/pip/wheel.py", line 396, in _get_script_text
    "import_name": entry.suffix.split(".")[0],
AttributeError: 'NoneType' object has no attribute 'split'

(u2fval.with.wheel) # deactivate 
```
but not without wheel : 
```
# rm -rf .cache/pip/wheels/

# virtualenv --no-wheel u2fval.without.wheel
New python executable in u2fval.without.wheel/bin/python2
Also creating executable in u2fval.without.wheel/bin/python
Installing setuptools, pip...done.

# source u2fval.without.wheel/bin/activate

(u2fval.without.wheel) # pip list
pip (7.1.2)
setuptools (18.2)

(u2fval.without.wheel) # pip install u2fval
Collecting u2fval
  Using cached u2fval-0.9.0.tar.gz
Collecting python-u2flib-server>=3.1 (from u2fval)
  Using cached python-u2flib-server-3.2.0.tar.gz
Collecting SQLAlchemy (from u2fval)
  Using cached SQLAlchemy-1.0.8.tar.gz
Collecting WebOb (from u2fval)
  Using cached WebOb-1.4.1.tar.gz
Collecting cachetools (from u2fval)
  Using cached cachetools-1.1.1-py2.py3-none-any.whl
Collecting M2Crypto (from python-u2flib-server>=3.1->u2fval)
  Using cached M2Crypto-0.22.3.tar.gz
Collecting pyasn1>=0.1.7 (from python-u2flib-server>=3.1->u2fval)
  Using cached pyasn1-0.1.8.tar.gz
Collecting pyasn1-modules (from python-u2flib-server>=3.1->u2fval)
  Using cached pyasn1-modules-0.0.7.tar.gz
Installing collected packages: M2Crypto, pyasn1, pyasn1-modules, python-u2flib-server, SQLAlchemy, WebOb, cachetools, u2fval
  Running setup.py install for M2Crypto
  Running setup.py install for pyasn1
  Running setup.py install for pyasn1-modules
  Running setup.py install for python-u2flib-server
  Running setup.py install for SQLAlchemy
  Running setup.py install for WebOb
  Running setup.py install for u2fval
Successfully installed M2Crypto-0.22.3 SQLAlchemy-1.0.8 WebOb-1.4.1 cachetools-1.1.1 pyasn1-0.1.8 pyasn1-modules-0.0.7 python-u2flib-server-3.2.0 u2fval-0.9.0

(u2fval.without.wheel) # deactivate
```

**Comment by patatetom** [comment]
fixed with 48fb813bd854d3755f6689ee3a76723679aadf82
