### ISSUE TITLE
pip2

### ISSUE THREAD

**Issue by patatetom** [Yubico/u2fval#7]
hi,
can you clarify that it is necessary to use pip2 because in some environments, pip is realated to pip3.
```
# pip install u2fval
Collecting u2fval
  Using cached u2fval-0.9.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-k26b4ju1/u2fval/setup.py", line 35
        print "copying default settings..."
                                          ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-k26b4ju1/u2fval
```

**Comment by dainnilsson** [comment]
I've added a classifier to setup.py that states that only Python 2 is supported. We hope to support Python 3 at some point, but currently some of the dependencies this project has prevents us from doing so.
